### ISSUE TITLE
do you use this for anything?

### ISSUE THREAD

**Issue by danbri** [iand/microdata#1]
I've signed up to W3C's Web Platform WG to update the W3C version of the Microdata spec to track "microdata as it ended up being deployed". This is more about the data than its parsers but it would be good to know if you're putting the parser to use, and if you've encountered any issues...

**Comment by iand** [comment]
I'm not currently using it although I did for a while for an old project. I don't know of any other people using it.

**Comment by danbri** [comment]
Thanks @iand !
